# Generated by Django 3.1 on 2020-08-26 16:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SleepRaw",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("device_type", models.CharField(max_length=128)),
                ("device_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("sleep_phase", models.CharField(max_length=32)),
                ("sleep_phase_id", models.IntegerField()),
                (
                    "hr_series",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), size=None
                    ),
                ),
                (
                    "rr_series",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), size=None
                    ),
                ),
                (
                    "snoring_series",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SleepSummary",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("user_id", models.IntegerField()),
                ("device_type", models.CharField(max_length=128)),
                ("device_id", models.IntegerField()),
                ("breathing_disturbances_intensity", models.IntegerField()),
                ("deep_sleep_duration", models.IntegerField()),
                ("duration_to_sleep", models.IntegerField()),
                ("duration_to_wakeup", models.IntegerField()),
                ("hr_average", models.IntegerField()),
                ("hr_max", models.IntegerField()),
                ("hr_min", models.IntegerField()),
                ("light_sleep_duration", models.IntegerField()),
                ("rem_sleep_duration", models.IntegerField()),
                ("rr_average", models.IntegerField()),
                ("rr_max", models.IntegerField()),
                ("rr_min", models.IntegerField()),
                ("sleep_score", models.IntegerField()),
                ("snoring", models.IntegerField()),
                ("snoring_episode_count", models.IntegerField()),
                ("wakeup_count", models.IntegerField()),
                ("wakeup_duration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WithingsAuthentication",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_token", models.CharField(max_length=128)),
                ("refresh_token", models.CharField(max_length=128)),
                ("expires_in", models.IntegerField()),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("valid_to", models.DateTimeField()),
                (
                    "scope",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=32), size=16
                    ),
                ),
                ("token_type", models.CharField(default="Bearer", max_length=128)),
                ("user_id", models.IntegerField()),
                ("demo", models.BooleanField()),
                ("expired", models.BooleanField()),
            ],
        ),
    ]
