# Generated by Django 3.1 on 2020-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0002_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weight", name="weight", field=models.FloatField(null=True),
        ),
    ]
