# Generated by Django 3.1 on 2020-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0003_auto_20200831_1354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleepsummary",
            name="deep_sleep_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="hr_average",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="hr_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="hr_min",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="light_sleep_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="rem_sleep_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="rr_average",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="rr_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="rr_min",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="sleepsummary",
            name="sleep_score",
            field=models.IntegerField(null=True),
        ),
    ]
