# Generated by Django 3.1 on 2020-09-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0005_activityraw_activitysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitysummary",
            name="measurement_type",
            field=models.CharField(default="not_provided", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="active_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="calories",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="distance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="elevation",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="hr_average",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="hr_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="hr_min",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="hr_zone_intense_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="hr_zone_light_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="hr_zone_max_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="hr_zone_moderate_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="intense_activities_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="moderate_activities_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="soft_activities_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="steps",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="activitysummary",
            name="total_calories",
            field=models.FloatField(null=True),
        ),
    ]
