{
 "title": "Health overview",
 "time": { "from": "now-120d", "to": "now" },
 "panels": [
  { "title": "Sleep", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heart rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(a.obj->>'timestamp', 'YYYY-MM-DD\"T\"HH24:MI:SS+0000') as time, to_number(a.obj->>'value', 'FM9G999D99S') as hr\nFROM connector_sleepraw\nCROSS JOIN LATERAL jsonb_array_elements(to_jsonb(hr_series)) AS a(obj)\nWHERE start_date > $__timeFrom() AND end_date <= $__timeTo() AND (device_type = 'SLEEP_MONITOR' OR device_type = 'Aura Sensor V2')\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sleep phases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT start_date as time, CASE\n  WHEN sleep_phase_id = 0 THEN 3\n  WHEN sleep_phase_id = 1 THEN 1\n  WHEN sleep_phase_id = 2 THEN 0\n  WHEN sleep_phase_id = 3 THEN 2\nEND AS sleep_phase\nFROM connector_sleepraw\nWHERE start_date > $__timeFrom() AND end_date <= $__timeTo() AND (device_type = 'SLEEP_MONITOR' OR device_type = 'Aura Sensor V2')\nORDER BY start_date"
    }
   ]
  },
  {
   "title": "Respiration rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(a.obj->>'timestamp', 'YYYY-MM-DD\"T\"HH24:MI:SS+0000') as time, to_number(a.obj->>'value', 'FM9G999D99S') as rr\nFROM connector_sleepraw\nCROSS JOIN LATERAL jsonb_array_elements(to_jsonb(rr_series)) AS a(obj)\nWHERE start_date > $__timeFrom() AND end_date <= $__timeTo() AND (device_type = 'SLEEP_MONITOR' OR device_type = 'Aura Sensor V2')\nORDER BY time"
    }
   ]
  },
  {
   "title": "Snoring",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT to_timestamp(a.obj->>'timestamp', 'YYYY-MM-DD\"T\"HH24:MI:SS+0000') as time, to_number(a.obj->>'value', 'FM9G999D99S') as snor\nFROM connector_sleepraw\nCROSS JOIN LATERAL jsonb_array_elements(to_jsonb(snoring_series)) AS a(obj)\nWHERE start_date > $__timeFrom() AND end_date <= $__timeTo() AND (device_type = 'SLEEP_MONITOR' OR device_type = 'Aura Sensor V2')\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sleep score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  end_date AS \"time\",\n  sleep_score\nFROM connector_sleepsummary\nWHERE\n  $__timeFilter(end_date)\nORDER BY 1"
    }
   ]
  },
  { "title": "Nutrition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Daily calories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "kcal" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  calories,\n  meal\n  -- AVG(weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_weight\"\nFROM connector_nutrition\nWHERE\n  $__timeFilter(start_date) AND meal='Breakfast'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  calories,\n  meal\n  -- AVG(weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_weight\"\nFROM connector_nutrition\nWHERE\n  $__timeFilter(start_date) AND meal='Lunch'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  calories,\n  meal\n  -- AVG(weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_weight\"\nFROM connector_nutrition\nWHERE\n  $__timeFilter(start_date) AND meal='Dinner'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  calories,\n  meal\n  -- AVG(weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_weight\"\nFROM connector_nutrition\nWHERE\n  $__timeFilter(start_date) AND meal='Snacks'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  start_date AS \"time\",\n  SUM(calories) OVER (PARTITION BY start_date) AS \"total_calories\"\n  -- AVG(weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_weight\"\nFROM connector_nutrition\nWHERE\n  $__timeFilter(start_date)\nORDER BY 1"
    }
   ]
  },
  { "title": "Body weight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Weight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "kg" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  weight,\n  AVG(weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_weight\"\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Muscle-to-fat ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "kg" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  muscle_mass/fat_mass_weight,\n  AVG(muscle_mass/fat_mass_weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_mtf_ratio\"\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Fat [kg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "kg" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  fat_mass_weight,\n  AVG(fat_mass_weight) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_fat\"\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Muscle [kg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "kg" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  muscle_mass,\n  AVG(muscle_mass) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_muscle\"\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Fat [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  fat_ratio,\n  AVG(fat_ratio) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_fat_ratio\"\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Muscle [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  100*muscle_mass/weight AS \"mass_ratio\",\n  AVG(100*muscle_mass/weight) OVER (ORDER BY measured_at ASC ROWS 14 PRECEDING) AS \"average_muscle_ratio\"\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pulse wave velocity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "m/s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  pulse_wave_velocity\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Water [kg]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "kg" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  hydration,\n  AVG(hydration) OVER (ORDER BY measured_at ASC ROWS 7 PRECEDING) AS \"average_hydration\"\nFROM connector_weight\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  { "title": "Daily activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Heart rate [aggregated]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  hr_average\nFROM connector_activitysummary\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  hr_min\nFROM connector_activitysummary\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  hr_max\nFROM connector_activitysummary\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  steps AS \"heart_rate\"\nFROM connector_activityraw\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Heart rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  heart_rate AS \"heart_rate\"\nFROM connector_activityraw\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Steps [aggregated]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measured_at AS \"time\",\n  steps\nFROM connector_activitysummary\nWHERE\n  $__timeFilter(measured_at)\nORDER BY 1"
    }
   ]
  }
 ]
}