# Generated by Django 3.1 on 2020-09-10 19:11

from django.db import migrations, models
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0004_auto_20200901_1942"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityRaw",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("device_type", models.CharField(max_length=128)),
                ("device_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("measured_at", models.DateTimeField()),
                ("steps", models.IntegerField(null=True)),
                ("duration", models.IntegerField()),
                ("distance", models.FloatField(null=True)),
                ("elevation", models.IntegerField(null=True)),
                ("calories", models.FloatField(null=True)),
                ("heart_rate", models.IntegerField(null=True)),
                ("measurement_type", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ActivitySummary",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("device_type", models.CharField(max_length=128)),
                ("device_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("measured_at", models.DateTimeField()),
                ("is_tracker", models.BooleanField()),
                ("steps", models.IntegerField()),
                ("distance", models.FloatField()),
                ("elevation", models.FloatField()),
                ("calories", models.FloatField()),
                ("soft_activities_duration", models.IntegerField()),
                ("moderate_activities_duration", models.IntegerField()),
                ("intense_activities_duration", models.IntegerField()),
                ("active_duration", models.IntegerField()),
                ("total_calories", models.FloatField()),
                ("hr_average", models.IntegerField()),
                ("hr_min", models.IntegerField()),
                ("hr_max", models.IntegerField()),
                ("hr_zone_light_duration", models.IntegerField()),
                ("hr_zone_moderate_duration", models.IntegerField()),
                ("hr_zone_intense_duration", models.IntegerField()),
                ("hr_zone_max_duration", models.IntegerField()),
            ],
        ),
    ]
