# Generated by Django 3.1.5 on 2021-01-24 17:27

from django.db import migrations, models
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0006_auto_20200913_0824"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nutrition",
            fields=[
                (
                    "id",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("user_id", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Snacks", "Snacks"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[("MyFitnessPal", "MyFitnessPal")],
                        default="MyFitnessPal",
                        max_length=16,
                    ),
                ),
                ("calories", models.FloatField()),
                ("total_fat", models.FloatField()),
                ("saturated_fat", models.FloatField()),
                ("trans_fat", models.FloatField()),
                ("cholesterol", models.FloatField()),
                ("sodium", models.FloatField()),
                ("carbohydrates", models.FloatField()),
                ("sugar", models.FloatField()),
                ("fiber", models.FloatField()),
                ("protein", models.FloatField()),
            ],
        ),
    ]
