name: Test and build connector image

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:9.6
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run Tests
        working-directory: withconn
        env:
          DJANGO_SETTINGS_MODULE: withconn.settings.dev
          SECRET_KEY: fakekey
          ALLOWED_HOSTS: localhost,127.0.0.1
        run: |
          pipenv run python manage.py test

  docker-withconn:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare tags
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_REPO }}
          TAGS="${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
